(() => {
  const $=id=>document.getElementById(id);let timer=null,selectedPlaceId='';
  async function load(){try{const me=await window.TarotPortal.api('/api/member/me');if(!me.ok){$('#profileStatus').textContent='กรุณาลงชื่อใช้งานก่อนจัดการข้อมูลของคุณ';$('#profileForm').hidden=true;return}const md=await me.json(),u=md.user||{};$('#accountSummary').hidden=false;$('#accountSummary').innerHTML=`<strong>${escapeHtml(u.name||u.nickname||'บัญชีของคุณ')}</strong>${u.email?`<br><span>${escapeHtml(u.email)}</span>`:''}`;const r=await window.TarotPortal.api('/api/member/profile'),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'โหลดข้อมูลไม่สำเร็จ');$('#birthDate').value=d.profile?.birth_date||'';$('#birthTime').value=d.profile?.birth_time||'';$('#birthPlace').value=d.profile?.birth_place||'';selectedPlaceId=d.profile?.birth_place_id||'';$('#birthPlaceId').value=selectedPlaceId;$('#profileStatus').textContent=d.profile?'ข้อมูลของคุณพร้อมใช้งาน':'เพิ่มวันเดือนปีเกิดเพื่อเปิดใช้ดวงประจำวัน'}catch(e){$('#profileStatus').textContent=e?.message||'โหลดข้อมูลไม่สำเร็จ'}}
  async function searchPlaces(){const q=$('#birthPlace').value.trim();selectedPlaceId='';$('#birthPlaceId').value='';if(q.length<3){hideSuggestions();return}try{const r=await window.TarotPortal.api(`/api/member/places/autocomplete?q=${encodeURIComponent(q)}`),d=await r.json();if(!r.ok)throw new Error();renderSuggestions(d.suggestions||[])}catch{hideSuggestions()}}
  function renderSuggestions(items){const box=$('#placeSuggestions');box.replaceChildren();if(!items.length){hideSuggestions();return}items.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='place-option';b.innerHTML=`<strong>${escapeHtml(p.mainText||p.text)}</strong>${p.secondaryText?`<span>${escapeHtml(p.secondaryText)}</span>`:''}`;b.onclick=()=>{selectedPlaceId=p.placeId;$('#birthPlaceId').value=p.placeId;$('#birthPlace').value=p.text;hideSuggestions()};box.append(b)});box.hidden=false}
  function hideSuggestions(){$('#placeSuggestions').hidden=true}
  async function save(e){e.preventDefault();const btn=$('#saveProfile');btn.disabled=true;$('#profileStatus').textContent='กำลังบันทึก…';try{const payload={birthDate:$('#birthDate').value,birthTime:$('#birthTime').value,birthPlace:$('#birthPlace').value,birthPlaceId:selectedPlaceId};const r=await window.TarotPortal.api('/api/member/profile',{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'บันทึกข้อมูลไม่สำเร็จ');selectedPlaceId=d.profile?.birth_place_id||'';$('#birthPlaceId').value=selectedPlaceId;$('#birthPlace').value=d.profile?.birth_place||'';$('#profileStatus').textContent='บันทึกข้อมูลแล้ว'}catch(e){$('#profileStatus').textContent=e?.message||'บันทึกข้อมูลไม่สำเร็จ'}finally{btn.disabled=false}}
  function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  addEventListener('DOMContentLoaded',()=>{$('#profileForm').addEventListener('submit',save);$('#birthPlace').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(searchPlaces,350)});document.addEventListener('click',e=>{if(!e.target.closest('.place-field'))hideSuggestions()});load()});
})();